// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdqbnzxsiwlfwgrhkpzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcWJuenhzaXdsZndncmhrcHpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MzU0MTYsImV4cCI6MjA1NzIxMTQxNn0.CFBmd57Holl_rq-wJ353J1iAvY81ZcEwZHfKWJAVVk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);